# Generated by Django 3.2.7 on 2021-09-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=150, unique=True)),
                ('payoutaddress', models.CharField(blank=True, max_length=150)),
                ('amountmined', models.CharField(blank=True, max_length=150)),
                ('amountachievedafterded', models.CharField(blank=True, max_length=150)),
                ('currentcoin', models.CharField(blank=True, max_length=150)),
                ('minespeed', models.CharField(blank=True, max_length=150)),
                ('minerconnected', models.BooleanField(default=False)),
                ('nextpayout', models.CharField(blank=True, max_length=150)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Accounts',
                'verbose_name_plural': 'Accounts',
                'db_table': 'auth_user',
            },
        ),
        migrations.AddIndex(
            model_name='userbase',
            index=models.Index(fields=['id', 'phone', 'first_name', 'last_name', 'email', 'is_active'], name='auth_user_id_2436f6_idx'),
        ),
    ]
