# Generated by Django 3.2.7 on 2021-09-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='phone',
            field=models.CharField(default=123, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
