# Generated by Django 3.2.7 on 2021-10-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userbase_watcherlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='binance_profile_token',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
