# Generated by Django 3.2.7 on 2021-10-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userbase_binance_profile_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='profit_today',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userbase',
            name='profit_yesterday',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
