# Generated by Django 3.2.7 on 2022-05-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211014_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='withdrawn_amount',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
