# Generated by Django 3.2.7 on 2022-07-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userbase_withdrawn_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='in_staking',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userbase',
            name='in_wallet_amount',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
