# Generated by Django 3.2.7 on 2022-07-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220725_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='in_staking',
            field=models.CharField(default=0, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='in_wallet_amount',
            field=models.CharField(default=0, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='withdrawn_amount',
            field=models.CharField(default=0, max_length=150, null=True),
        ),
    ]
