# Generated by Django 3.2.7 on 2022-07-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220725_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='in_staking',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userbase',
            name='in_wallet_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userbase',
            name='withdrawn_amount',
            field=models.FloatField(default=0),
        ),
    ]
